<?php
/**
 * ACF Field Definitions for Adverion Theme
 *
 * @package adverion
 */

/**
 * Register ACF Fields for Footer Options
 */
if (function_exists('acf_add_options_page')) {
    // Add Options Page
    acf_add_options_page(array(
        'page_title'    => 'Footer Settings',
        'menu_title'    => 'Footer Settings',
        'menu_slug'     => 'footer-settings',
        'capability'    => 'edit_posts',
        'redirect'      => false
    ));
    
    // Add Footer Fields
    acf_add_local_field_group(array(
        'key' => 'group_footer_settings',
        'title' => 'Footer Settings',
        'fields' => array(
            array(
                'key' => 'field_footer_description',
                'label' => 'Footer Description',
                'name' => 'footer_description',
                'type' => 'textarea',
                'instructions' => 'Enter the description text for the footer brand section.',
                'default_value' => 'Data-driven digital marketing for enterprise growth.',
                'placeholder' => 'Data-driven digital marketing for enterprise growth.',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_services_title',
                'label' => 'Services Section Title',
                'name' => 'services_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the Services section in footer.',
                'default_value' => 'Services',
                'placeholder' => 'Services',
                'maxlength' => 50,
            ),
            array(
                'key' => 'field_company_title',
                'label' => 'Company Section Title',
                'name' => 'company_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the Company section in footer.',
                'default_value' => 'Company',
                'placeholder' => 'Company',
                'maxlength' => 50,
            ),
            array(
                'key' => 'field_copyright_text',
                'label' => 'Copyright Text',
                'name' => 'copyright_text',
                'type' => 'text',
                'instructions' => 'Enter the copyright text for footer bottom.',
                'default_value' => 'All rights reserved.',
                'placeholder' => 'All rights reserved.',
                'maxlength' => 100,
            ),
            array(
                'key' => 'field_newsletter_title',
                'label' => 'Newsletter Section Title',
                'name' => 'newsletter_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the newsletter section.',
                'default_value' => 'Stay Updated',
                'placeholder' => 'Stay Updated',
                'maxlength' => 50,
            ),
            array(
                'key' => 'field_newsletter_description',
                'label' => 'Newsletter Description',
                'name' => 'newsletter_description',
                'type' => 'textarea',
                'instructions' => 'Enter the description text for the newsletter section.',
                'default_value' => 'Subscribe to our newsletter for the latest updates and insights.',
                'placeholder' => 'Subscribe to our newsletter for the latest updates and insights.',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_show_contact_info',
                'label' => 'Show Contact Information',
                'name' => 'show_contact_info',
                'type' => 'true_false',
                'instructions' => 'Toggle to show/hide contact information in footer.',
                'default_value' => 0,
                'ui' => 1,
            ),
            array(
                'key' => 'field_contact_email',
                'label' => 'Contact Email',
                'name' => 'contact_email',
                'type' => 'email',
                'instructions' => 'Enter the contact email address.',
                'default_value' => '',
                'placeholder' => 'contact@example.com',
            ),
            array(
                'key' => 'field_contact_phone',
                'label' => 'Contact Phone',
                'name' => 'contact_phone',
                'type' => 'text',
                'instructions' => 'Enter the contact phone number.',
                'default_value' => '',
                'placeholder' => '+1 (555) 123-4567',
                'maxlength' => 20,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'footer-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => 'Footer configuration options for the Adverion theme.',
    ));
}

/**
 * Register Page Builder ACF Fields based on template structure
 */
add_action('acf/include_fields', function() {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_page_builder',
        'title' => 'Page Builder',
        'fields' => array(
            array(
                'key' => 'field_page_builder',
                'label' => 'Page Builder',
                'name' => 'page_builder',
                'type' => 'flexible_content',
                'instructions' => 'Build your page using flexible content blocks.',
                'required' => 0,
                'button_label' => 'Add Section',
                'layouts' => array(
                    // Hero Section Layout
                    'layout_hero_section' => array(
                        'key' => 'layout_hero_section',
                        'name' => 'hero_section',
                        'label' => 'Hero Section',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_hero_title',
                                'label' => 'Hero Title',
                                'name' => 'hero_title',
                                'type' => 'text',
                                'instructions' => 'Enter the main hero title. Use <span> tags for gradient text.',
                                'required' => 1,
                                'default_value' => 'Grow Your Brand Faster With <span class="text-gradient">Data-Driven</span> Digital Marketing',
                                'placeholder' => 'Enter hero title...',
                            ),
                            array(
                                'key' => 'field_hero_subtitle',
                                'label' => 'Hero Subtitle',
                                'name' => 'hero_subtitle',
                                'type' => 'textarea',
                                'instructions' => 'Enter the hero subtitle/description.',
                                'required' => 1,
                                'default_value' => 'Adverion helps businesses scale through performance marketing, SEO, and conversion-focused strategies.',
                                'placeholder' => 'Enter hero subtitle...',
                                'rows' => 3,
                                'new_lines' => 'br',
                            ),
                            array(
                                'key' => 'field_hero_primary_button',
                                'label' => 'Primary Button Text',
                                'name' => 'hero_primary_button',
                                'type' => 'text',
                                'instructions' => 'Enter the text for the primary CTA button.',
                                'required' => 1,
                                'default_value' => 'Get Free Strategy Call',
                                'placeholder' => 'Primary button text...',
                            ),
                            array(
                                'key' => 'field_hero_primary_link',
                                'label' => 'Primary Button Link',
                                'name' => 'hero_primary_link',
                                'type' => 'url',
                                'instructions' => 'Enter the URL for the primary button.',
                                'required' => 0,
                                'placeholder' => 'https://example.com/contact',
                            ),
                            array(
                                'key' => 'field_hero_secondary_button',
                                'label' => 'Secondary Button Text',
                                'name' => 'hero_secondary_button',
                                'type' => 'text',
                                'instructions' => 'Enter the text for the secondary button.',
                                'required' => 0,
                                'default_value' => 'View Our Work',
                                'placeholder' => 'Secondary button text...',
                            ),
                            array(
                                'key' => 'field_hero_secondary_link',
                                'label' => 'Secondary Button Link',
                                'name' => 'hero_secondary_link',
                                'type' => 'url',
                                'instructions' => 'Enter the URL for the secondary button.',
                                'required' => 0,
                                'placeholder' => 'https://example.com/portfolio',
                            ),
                        ),
                    ),
                    // About Story Layout
                    'layout_about_story' => array(
                        'key' => 'layout_about_story',
                        'name' => 'about_story',
                        'label' => 'About Story',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_story_title',
                                'label' => 'Story Title',
                                'name' => 'story_title',
                                'type' => 'text',
                                'instructions' => 'Enter the main title for the about story section.',
                                'required' => 1,
                                'placeholder' => 'Our Story',
                            ),
                            array(
                                'key' => 'field_story_content',
                                'label' => 'Story Content',
                                'name' => 'story_content',
                                'type' => 'wysiwyg',
                                'instructions' => 'Enter the main content for the about story section.',
                                'required' => 1,
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array(
                                'key' => 'field_story_image',
                                'label' => 'Story Image',
                                'name' => 'story_image',
                                'type' => 'image',
                                'instructions' => 'Upload an image for the about story section.',
                                'required' => 0,
                                'return_format' => 'id',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array(
                                'key' => 'field_image_position',
                                'label' => 'Image Position',
                                'name' => 'image_position',
                                'type' => 'select',
                                'instructions' => 'Choose the position of the image relative to the content.',
                                'required' => 1,
                                'choices' => array(
                                    'left' => 'Left',
                                    'right' => 'Right',
                                ),
                                'default_value' => 'left',
                            ),
                            array(
                                'key' => 'field_show_stats',
                                'label' => 'Show Statistics',
                                'name' => 'show_stats',
                                'type' => 'true_false',
                                'instructions' => 'Toggle to show/hide statistics section.',
                                'default_value' => 1,
                                'ui' => 1,
                            ),
                            array(
                                'key' => 'field_stats',
                                'label' => 'Statistics',
                                'name' => 'stats',
                                'type' => 'repeater',
                                'instructions' => 'Add statistics items to display.',
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_show_stats',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                                'layout' => 'table',
                                'button_label' => 'Add Stat',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_stat_number',
                                        'label' => 'Stat Number',
                                        'name' => 'stat_number',
                                        'type' => 'text',
                                        'instructions' => 'Enter the statistic number (e.g., 500+, 25%).',
                                        'required' => 1,
                                        'wrapper' => array('width' => '50'),
                                        'placeholder' => '500+',
                                    ),
                                    array(
                                        'key' => 'field_stat_suffix',
                                        'label' => 'Stat Suffix',
                                        'name' => 'stat_suffix',
                                        'type' => 'text',
                                        'instructions' => 'Enter suffix for the number (e.g., %, +, years).',
                                        'required' => 0,
                                        'wrapper' => array('width' => '25'),
                                        'placeholder' => '%',
                                    ),
                                    array(
                                        'key' => 'field_stat_label',
                                        'label' => 'Stat Label',
                                        'name' => 'stat_label',
                                        'type' => 'text',
                                        'instructions' => 'Enter the statistic label.',
                                        'required' => 1,
                                        'wrapper' => array('width' => '75'),
                                        'placeholder' => 'Happy Clients',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    // Services Layout
                    'layout_services' => array(
                        'key' => 'layout_services',
                        'name' => 'services',
                        'label' => 'Services',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_services_section_title',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'instructions' => 'Enter the section title.',
                                'required' => 0,
                                'placeholder' => 'Our Services',
                            ),
                            array(
                                'key' => 'field_services_section_subtitle',
                                'label' => 'Section Subtitle',
                                'name' => 'section_subtitle',
                                'type' => 'textarea',
                                'instructions' => 'Enter the section subtitle.',
                                'required' => 0,
                                'placeholder' => 'We offer comprehensive digital marketing solutions.',
                                'rows' => 3,
                            ),
                            array(
                                'key' => 'field_services_list',
                                'label' => 'Services',
                                'name' => 'services',
                                'type' => 'repeater',
                                'instructions' => 'Add services to display.',
                                'layout' => 'row',
                                'button_label' => 'Add Service',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_service_icon',
                                        'label' => 'Service Icon',
                                        'name' => 'service_icon',
                                        'type' => 'image',
                                        'instructions' => 'Upload an icon for the service.',
                                        'required' => 0,
                                        'return_format' => 'id',
                                        'preview_size' => 'thumbnail',
                                        'wrapper' => array('width' => '33'),
                                    ),
                                    array(
                                        'key' => 'field_service_font_awesome',
                                        'label' => 'Font Awesome Icon',
                                        'name' => 'font_awesome_class',
                                        'type' => 'text',
                                        'instructions' => 'Enter Font Awesome class (e.g., fas fa-chart-line). <a href="https://fontawesome.com/icons" target="_blank">Browse icons</a>',
                                        'required' => 0,
                                        'placeholder' => 'fas fa-chart-line',
                                        'wrapper' => array('width' => '33'),
                                    ),
                                    array(
                                        'key' => 'field_service_image',
                                        'label' => 'Service Image',
                                        'name' => 'service_image',
                                        'type' => 'image',
                                        'instructions' => 'Upload an image for the service.',
                                        'required' => 0,
                                        'return_format' => 'id',
                                        'preview_size' => 'medium',
                                        'wrapper' => array('width' => '34'),
                                    ),
                                    array(
                                        'key' => 'field_service_title',
                                        'label' => 'Service Title',
                                        'name' => 'service_title',
                                        'type' => 'text',
                                        'instructions' => 'Enter the service title.',
                                        'required' => 1,
                                        'placeholder' => 'Digital Marketing',
                                        'wrapper' => array('width' => '50'),
                                    ),
                                    array(
                                        'key' => 'field_service_link',
                                        'label' => 'Service Link',
                                        'name' => 'service_link',
                                        'type' => 'url',
                                        'instructions' => 'Enter a URL for the service (optional).',
                                        'required' => 0,
                                        'placeholder' => 'https://example.com/service',
                                        'wrapper' => array('width' => '50'),
                                    ),
                                    array(
                                        'key' => 'field_service_description',
                                        'label' => 'Service Description',
                                        'name' => 'service_description',
                                        'type' => 'wysiwyg',
                                        'instructions' => 'Enter the service description.',
                                        'required' => 1,
                                        'tabs' => 'text',
                                        'toolbar' => 'basic',
                                        'media_upload' => 0,
                                        'wrapper' => array('width' => '100'),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    // Features Layout
                    'layout_features' => array(
                        'key' => 'layout_features',
                        'name' => 'features',
                        'label' => 'Features',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_features_section_title',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'instructions' => 'Enter the section title.',
                                'required' => 0,
                                'placeholder' => 'Why Choose Us',
                            ),
                            array(
                                'key' => 'field_features_section_subtitle',
                                'label' => 'Section Subtitle',
                                'name' => 'section_subtitle',
                                'type' => 'textarea',
                                'instructions' => 'Enter the section subtitle.',
                                'required' => 0,
                                'placeholder' => 'Discover what makes us different.',
                                'rows' => 3,
                            ),
                            array(
                                'key' => 'field_features_list',
                                'label' => 'Features',
                                'name' => 'features',
                                'type' => 'repeater',
                                'instructions' => 'Add features to display.',
                                'layout' => 'table',
                                'button_label' => 'Add Feature',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_feature_icon',
                                        'label' => 'Feature Icon',
                                        'name' => 'feature_icon',
                                        'type' => 'image',
                                        'instructions' => 'Upload an icon for the feature.',
                                        'required' => 0,
                                        'return_format' => 'id',
                                        'preview_size' => 'thumbnail',
                                    ),
                                    array(
                                        'key' => 'field_feature_font_awesome',
                                        'label' => 'Font Awesome Class',
                                        'name' => 'font_awesome_class',
                                        'type' => 'text',
                                        'instructions' => 'Enter Font Awesome class (e.g., fas fa-rocket).',
                                        'required' => 0,
                                        'placeholder' => 'fas fa-rocket',
                                    ),
                                    array(
                                        'key' => 'field_feature_title',
                                        'label' => 'Feature Title',
                                        'name' => 'feature_title',
                                        'type' => 'text',
                                        'instructions' => 'Enter the feature title.',
                                        'required' => 1,
                                        'placeholder' => 'Expert Team',
                                    ),
                                    array(
                                        'key' => 'field_feature_description',
                                        'label' => 'Feature Description',
                                        'name' => 'feature_description',
                                        'type' => 'wysiwyg',
                                        'instructions' => 'Enter the feature description.',
                                        'required' => 1,
                                        'tabs' => 'text',
                                        'toolbar' => 'basic',
                                        'media_upload' => 0,
                                    ),
                                ),
                            ),
                        ),
                    ),
                    // Process Layout
                    'layout_process' => array(
                        'key' => 'layout_process',
                        'name' => 'process',
                        'label' => 'Process',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_process_section_title',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'instructions' => 'Enter the section title.',
                                'required' => 0,
                                'placeholder' => 'Our Process',
                            ),
                            array(
                                'key' => 'field_process_section_subtitle',
                                'label' => 'Section Subtitle',
                                'name' => 'section_subtitle',
                                'type' => 'textarea',
                                'instructions' => 'Enter the section subtitle.',
                                'required' => 0,
                                'placeholder' => 'How we work with you.',
                                'rows' => 3,
                            ),
                            array(
                                'key' => 'field_process_steps',
                                'label' => 'Process Steps',
                                'name' => 'process_steps',
                                'type' => 'repeater',
                                'instructions' => 'Add process steps.',
                                'layout' => 'table',
                                'button_label' => 'Add Step',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_step_title',
                                        'label' => 'Step Title',
                                        'name' => 'step_title',
                                        'type' => 'text',
                                        'instructions' => 'Enter the step title.',
                                        'required' => 1,
                                        'placeholder' => 'Discovery',
                                    ),
                                    array(
                                        'key' => 'field_step_description',
                                        'label' => 'Step Description',
                                        'name' => 'step_description',
                                        'type' => 'wysiwyg',
                                        'instructions' => 'Enter the step description.',
                                        'required' => 1,
                                        'tabs' => 'text',
                                        'toolbar' => 'basic',
                                        'media_upload' => 0,
                                    ),
                                ),
                            ),
                        ),
                    ),
                    // Results Layout
                    'layout_results' => array(
                        'key' => 'layout_results',
                        'name' => 'results',
                        'label' => 'Results',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_results_section_title',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'instructions' => 'Enter the section title.',
                                'required' => 0,
                                'placeholder' => 'Our Results',
                            ),
                            array(
                                'key' => 'field_results_section_subtitle',
                                'label' => 'Section Subtitle',
                                'name' => 'section_subtitle',
                                'type' => 'textarea',
                                'instructions' => 'Enter the section subtitle.',
                                'required' => 0,
                                'placeholder' => 'Numbers that speak for themselves.',
                                'rows' => 3,
                            ),
                            array(
                                'key' => 'field_results_list',
                                'label' => 'Results',
                                'name' => 'results',
                                'type' => 'repeater',
                                'instructions' => 'Add results to display.',
                                'layout' => 'table',
                                'button_label' => 'Add Result',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_result_number',
                                        'label' => 'Result Number',
                                        'name' => 'result_number',
                                        'type' => 'text',
                                        'instructions' => 'Enter the result number.',
                                        'required' => 1,
                                        'wrapper' => array('width' => '50'),
                                        'placeholder' => '500',
                                    ),
                                    array(
                                        'key' => 'field_result_suffix',
                                        'label' => 'Result Suffix',
                                        'name' => 'result_suffix',
                                        'type' => 'text',
                                        'instructions' => 'Enter suffix (e.g., %, +, years).',
                                        'required' => 0,
                                        'wrapper' => array('width' => '25'),
                                        'placeholder' => '%',
                                    ),
                                    array(
                                        'key' => 'field_result_text',
                                        'label' => 'Result Text',
                                        'name' => 'result_text',
                                        'type' => 'text',
                                        'instructions' => 'Enter the result label.',
                                        'required' => 1,
                                        'wrapper' => array('width' => '75'),
                                        'placeholder' => 'Happy Clients',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    // Client Logos Layout
                    'layout_client_logos' => array(
                        'key' => 'layout_client_logos',
                        'name' => 'client_logos',
                        'label' => 'Client Logos',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_client_logos_section_title',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'instructions' => 'Enter the section title.',
                                'required' => 0,
                                'placeholder' => 'Trusted by Leading Brands',
                            ),
                            array(
                                'key' => 'field_client_logos_list',
                                'label' => 'Logos',
                                'name' => 'logos',
                                'type' => 'repeater',
                                'instructions' => 'Add client logos.',
                                'layout' => 'table',
                                'button_label' => 'Add Logo',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_logo_image',
                                        'label' => 'Logo Image',
                                        'name' => 'logo_image',
                                        'type' => 'image',
                                        'instructions' => 'Upload the client logo.',
                                        'required' => 0,
                                        'return_format' => 'id',
                                        'preview_size' => 'medium',
                                    ),
                                    array(
                                        'key' => 'field_logo_text',
                                        'label' => 'Logo Text',
                                        'name' => 'logo_text',
                                        'type' => 'text',
                                        'instructions' => 'Enter text to display if no image (fallback).',
                                        'required' => 0,
                                        'placeholder' => 'Client Name',
                                    ),
                                    array(
                                        'key' => 'field_logo_link',
                                        'label' => 'Logo Link',
                                        'name' => 'logo_link',
                                        'type' => 'url',
                                        'instructions' => 'Enter a URL for the logo (optional).',
                                        'required' => 0,
                                        'placeholder' => 'https://example.com',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    // CTA Layout
                    'layout_cta' => array(
                        'key' => 'layout_cta',
                        'name' => 'cta',
                        'label' => 'Call to Action',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_cta_section_title',
                                'label' => 'Section Title',
                                'name' => 'section_title',
                                'type' => 'text',
                                'instructions' => 'Enter the CTA title.',
                                'required' => 1,
                                'placeholder' => 'Ready to Grow Your Business?',
                            ),
                            array(
                                'key' => 'field_cta_section_subtitle',
                                'label' => 'Section Subtitle',
                                'name' => 'section_subtitle',
                                'type' => 'textarea',
                                'instructions' => 'Enter the CTA subtitle.',
                                'required' => 0,
                                'placeholder' => 'Let\'s discuss how we can help you achieve your goals.',
                                'rows' => 3,
                            ),
                            array(
                                'key' => 'field_cta_primary_text',
                                'label' => 'Primary Button Text',
                                'name' => 'primary_cta_text',
                                'type' => 'text',
                                'instructions' => 'Enter the primary button text.',
                                'required' => 1,
                                'placeholder' => 'Get Started',
                            ),
                            array(
                                'key' => 'field_cta_primary_url',
                                'label' => 'Primary Button URL',
                                'name' => 'primary_cta_url',
                                'type' => 'url',
                                'instructions' => 'Enter the primary button URL.',
                                'required' => 1,
                                'placeholder' => 'https://example.com/contact',
                            ),
                            array(
                                'key' => 'field_cta_secondary_text',
                                'label' => 'Secondary Button Text',
                                'name' => 'secondary_cta_text',
                                'type' => 'text',
                                'instructions' => 'Enter the secondary button text.',
                                'required' => 0,
                                'placeholder' => 'Learn More',
                            ),
                            array(
                                'key' => 'field_cta_secondary_url',
                                'label' => 'Secondary Button URL',
                                'name' => 'secondary_cta_url',
                                'type' => 'url',
                                'instructions' => 'Enter the secondary button URL.',
                                'required' => 0,
                                'placeholder' => 'https://example.com/about',
                            ),
                            array(
                                'key' => 'field_cta_background_style',
                                'label' => 'Background Style',
                                'name' => 'background_style',
                                'type' => 'select',
                                'instructions' => 'Choose the background style.',
                                'required' => 1,
                                'choices' => array(
                                    'gradient' => 'Gradient (Default)',
                                    'solid' => 'Solid Color',
                                    'image' => 'Background Image',
                                ),
                                'default_value' => 'gradient',
                            ),
                            array(
                                'key' => 'field_cta_background_color',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'type' => 'color_picker',
                                'instructions' => 'Choose a background color (for solid style).',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_cta_background_style',
                                            'operator' => '==',
                                            'value' => 'solid',
                                        ),
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_cta_background_image',
                                'label' => 'Background Image',
                                'name' => 'background_image',
                                'type' => 'image',
                                'instructions' => 'Upload a background image (for image style).',
                                'required' => 0,
                                'return_format' => 'id',
                                'preview_size' => 'large',
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_cta_background_style',
                                            'operator' => '==',
                                            'value' => 'image',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => 'Page builder for creating flexible page layouts.',
    ));
});